# 1. Importing libraries and Dataset

In [27]:
import pandas as pd
import re
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [9]:
res = pd.read_csv('resumes.csv')
job = pd.read_csv('job_descriptions.csv')

In [7]:
res.head()

,resume_id,resume_text,experience_years
0,R1,deep learning tensorflow keras python,1
1,R2,sas clinical sdtm adam tlf cdisc,3
2,R3,sql excel powerbi data analysis reporting,3
3,R4,python pandas numpy machine learning sql stati...,1
4,R5,deep learning tensorflow keras python,1

In [10]:
job.head()

  job_id                 job_role                     job_description
0     J1             Data Analyst     sql excel powerbi data analysis
1     J2           Data Scientist  python machine learning statistics
2     J3  Clinical SAS Programmer          sas clinical sdtm adam tlf

In [12]:
res.shape[0]

300

In [13]:
res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   resume_id         300 non-null    object
 1   resume_text       300 non-null    object
 2   experience_years  300 non-null    int64
dtypes: int64(1), object(2)
memory usage: 7.2+ KB

In [14]:
job.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           3 non-null      object
 1   job_role         3 non-null      object
 2   job_description  3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

# Text preprocessing

#### Converting all the text to lower cases

In [20]:
res["resume_text_lower"] = res["resume_text"].str.lower()
print(res["resume_text_lower"].head(2))

0    deep learning tensorflow keras python
1         sas clinical sdtm adam tlf cdisc
Name: resume_text_lower, dtype: object

In [24]:
job["job_role_lower"]=job["job_role"].str.lower()
print(job["job_role_lower"].head(2))

0      data analyst
1    data scientist
Name: job_role_lower, dtype: object

In [25]:
job["job_description_lower"]=job["job_description"].str.lower()
print(job["job_description_lower"].head(2))

0       sql excel powerbi data analysis
1    python machine learning statistics
Name: job_description_lower, dtype: object

#### Cheking special characters

In [28]:
res["has_special_chars"] = res["resume_text"].apply(
    lambda x: bool(re.search(r"[^a-zA-Z0-9 ]", x))
)
print(res["has_special_chars"])

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297    False
298    False
299    False
Name: has_special_chars, Length: 300, dtype: bool